[log]
level="DEBUG"
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http.tls]


[providers.file]
  filename = "/etc/traefik/dynamic_conf.toml"


